In [15]:
import scipy.io as sio
import pandas as pd
import numpy as np

In [6]:
test = sio.loadmat('../../data/graf_V1data/array_1.mat')

In [9]:
test

{'__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: MACI, Created on: Thu Apr 26 15:49:10 2012',
 '__version__': '1.0',
 'array_ind': array([[1]], dtype=uint8),
 'i': array([[147]], dtype=uint8),
 'ind': array([[      1],
        [      2],
        [      3],
        ..., 
        [2780807],
        [2780808],
        [2780809]], dtype=int32),
 'j': array([[5]], dtype=uint8),
 'k': array([[3600]], dtype=uint16),
 'mat_path': array(['neural_data/567/567l002p19.mat'], 
       dtype='<U30'),
 'n_class': array([[5]], dtype=uint8),
 'n_electrode': array([[96]], dtype=uint8),
 'n_neur': array([[147]], dtype=uint8),
 'n_ori': array([[72]], dtype=uint8),
 'n_trial': array([[50]], dtype=uint8),
 'n_trial_tot': array([[3600]], dtype=uint16),
 'neur_param': array([[ 3,  1],
        [ 3,  2],
        [ 3,  3],
        [ 4,  1],
        [ 7,  1],
        [ 9,  1],
        [ 9,  2],
        [ 9,  3],
        [10,  1],
        [10,  2],
        [11,  1],
        [11,  2],
        [13,

In [18]:
test.keys()

dict_keys(['tf_tot', 'passID', 'j', 'ind', 'ori', 'array_ind', 'n_ori', 'slotID', '__version__', 'spk_res', 'sf_tot', 't_start', 't_pres', 't_sync', '__header__', '__globals__', 'n_class', 'neur_param', 'n_neur', 'i', 't_spont', 'n_trial_tot', 'scr_y_tot', 'spk_times', 'save_path', 'n_electrode', 's_tot', 'scr_x_tot', 'nev_path', 't_stim', 't_vec', 'n_trial', 'k', 'ori_tot', 'mat_path'])

In [24]:
test['tf_tot']

array([[ 6.25,  6.25,  6.25, ...,  6.25,  6.25,  6.25]])

In [25]:
test['spk_times']

array([[ array([[  254.16666667],
       [  467.96666667],
       [  735.56666667],
       [  959.2       ],
       [ 1037.3       ],
       [ 1622.96666667]]),
        array([], shape=(0, 1), dtype=uint8),
        array([[  435.06666667],
       [ 2064.        ]]), ...,
        array([[ 501.06666667]]), array([[ 2527.9]]),
        array([[ 382.06666667],
       [ 630.33333333],
       [ 701.43333333],
       [ 713.4       ],
       [ 737.6       ],
       [ 772.73333333],
       [ 837.76666667],
       [ 913.63333333],
       [ 943.26666667]])],
       [array([[ 240.9       ],
       [ 413.76666667]]),
        array([], shape=(0, 1), dtype=uint8), array([[ 350.86666667]]),
        ...,
        array([[ 683.86666667],
       [ 714.63333333],
       [ 736.03333333]]),
        array([[ 1297.7]]),
        array([[ 358.63333333],
       [ 439.66666667],
       [ 674.5       ],
       [ 881.4       ],
       [ 883.86666667],
       [ 961.53333333]])],
       [array([], shape=(0, 1), dtype=u